#!/usr/bin/env python3
#
# Import the compiled Qt resource module so that :/images/... paths are
# registered with the Qt resource system. resources_rc.py is generated by
# `pyside6-rcc` (make ui) and is gitignored — the try/except handles a fresh
# checkout before `make ui` has been run.
try:
    from . import resources_rc as _rc  # noqa: F401
except ImportError:
    pass
