# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_timeplots.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimePlots(object):
    def setupUi(self, TimePlots):
        TimePlots.setObjectName("TimePlots")
        TimePlots.resize(609, 436)
        self.layoutTimePlots = QtWidgets.QVBoxLayout(TimePlots)
        self.layoutTimePlots.setObjectName("layoutTimePlots")
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setObjectName("layoutActions")
        self.btnTimeSeries = QtWidgets.QToolButton(TimePlots)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/32x32/tool_histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTimeSeries.setIcon(icon)
        self.btnTimeSeries.setCheckable(True)
        self.btnTimeSeries.setAutoExclusive(True)
        self.btnTimeSeries.setObjectName("btnTimeSeries")
        self.layoutActions.addWidget(self.btnTimeSeries)
        self.btnPieChart = QtWidgets.QToolButton(TimePlots)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/32x32/tool_piechart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPieChart.setIcon(icon1)
        self.btnPieChart.setCheckable(True)
        self.btnPieChart.setAutoExclusive(True)
        self.btnPieChart.setObjectName("btnPieChart")
        self.layoutActions.addWidget(self.btnPieChart)
        self.btnTextOutput = QtWidgets.QToolButton(TimePlots)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/32x32/mimetext_csv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTextOutput.setIcon(icon2)
        self.btnTextOutput.setCheckable(True)
        self.btnTextOutput.setAutoExclusive(True)
        self.btnTextOutput.setObjectName("btnTextOutput")
        self.layoutActions.addWidget(self.btnTextOutput)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutActions.addItem(spacerItem)
        self.lblStart = QtWidgets.QLabel(TimePlots)
        self.lblStart.setObjectName("lblStart")
        self.layoutActions.addWidget(self.lblStart)
        self.deStart = QtWidgets.QDateEdit(TimePlots)
        self.deStart.setCalendarPopup(True)
        self.deStart.setObjectName("deStart")
        self.layoutActions.addWidget(self.deStart)
        self.lblEnd = QtWidgets.QLabel(TimePlots)
        self.lblEnd.setObjectName("lblEnd")
        self.layoutActions.addWidget(self.lblEnd)
        self.deEnd = QtWidgets.QDateEdit(TimePlots)
        self.deEnd.setCalendarPopup(True)
        self.deEnd.setObjectName("deEnd")
        self.layoutActions.addWidget(self.deEnd)
        self.layoutTimePlots.addLayout(self.layoutActions)
        self.layoutDraw = QtWidgets.QVBoxLayout()
        self.layoutDraw.setSpacing(0)
        self.layoutDraw.setObjectName("layoutDraw")
        self.frmTextOutput = QtWidgets.QFrame(TimePlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frmTextOutput.sizePolicy().hasHeightForWidth())
        self.frmTextOutput.setSizePolicy(sizePolicy)
        self.frmTextOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTextOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTextOutput.setObjectName("frmTextOutput")
        self.layoutTextOutput = QtWidgets.QVBoxLayout(self.frmTextOutput)
        self.layoutTextOutput.setObjectName("layoutTextOutput")
        self.lblHtml = QtWidgets.QLabel(self.frmTextOutput)
        self.lblHtml.setObjectName("lblHtml")
        self.layoutTextOutput.addWidget(self.lblHtml)
        self.edtHtml = QtWidgets.QTextEdit(self.frmTextOutput)
        self.edtHtml.setObjectName("edtHtml")
        self.layoutTextOutput.addWidget(self.edtHtml)
        self.layoutCsv = QtWidgets.QHBoxLayout()
        self.layoutCsv.setObjectName("layoutCsv")
        self.lblCsv = QtWidgets.QLabel(self.frmTextOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCsv.sizePolicy().hasHeightForWidth())
        self.lblCsv.setSizePolicy(sizePolicy)
        self.lblCsv.setObjectName("lblCsv")
        self.layoutCsv.addWidget(self.lblCsv)
        self.cbCsvFull = QtWidgets.QCheckBox(self.frmTextOutput)
        self.cbCsvFull.setObjectName("cbCsvFull")
        self.layoutCsv.addWidget(self.cbCsvFull)
        self.layoutTextOutput.addLayout(self.layoutCsv)
        self.edtCsv = QtWidgets.QPlainTextEdit(self.frmTextOutput)
        self.edtCsv.setToolTip("")
        self.edtCsv.setObjectName("edtCsv")
        self.layoutTextOutput.addWidget(self.edtCsv)
        self.layoutDraw.addWidget(self.frmTextOutput)
        self.frmPlot = QtWidgets.QFrame(TimePlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frmPlot.sizePolicy().hasHeightForWidth())
        self.frmPlot.setSizePolicy(sizePolicy)
        self.frmPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPlot.setObjectName("frmPlot")
        self.layoutPlot = QtWidgets.QVBoxLayout(self.frmPlot)
        self.layoutPlot.setObjectName("layoutPlot")
        self.layoutDraw.addWidget(self.frmPlot)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutDraw.addItem(spacerItem1)
        self.layoutDraw.setStretch(0, 1)
        self.layoutDraw.setStretch(1, 1)
        self.layoutTimePlots.addLayout(self.layoutDraw)
        self.buttonBox = QtWidgets.QDialogButtonBox(TimePlots)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutTimePlots.addWidget(self.buttonBox)
        self.layoutTimePlots.setStretch(1, 1)

        self.retranslateUi(TimePlots)
        self.buttonBox.accepted.connect(TimePlots.accept)
        self.buttonBox.rejected.connect(TimePlots.reject)
        QtCore.QMetaObject.connectSlotsByName(TimePlots)
        TimePlots.setTabOrder(self.deStart, self.deEnd)
        TimePlots.setTabOrder(self.deEnd, self.edtHtml)
        TimePlots.setTabOrder(self.edtHtml, self.edtCsv)
        TimePlots.setTabOrder(self.edtCsv, self.btnTimeSeries)
        TimePlots.setTabOrder(self.btnTimeSeries, self.btnPieChart)
        TimePlots.setTabOrder(self.btnPieChart, self.btnTextOutput)

    def retranslateUi(self, TimePlots):
        _translate = QtCore.QCoreApplication.translate
        TimePlots.setWindowTitle(_translate("TimePlots", "Diagrammes"))
        self.btnTimeSeries.setToolTip(_translate("TimePlots", "Visualisation temporelle"))
        self.btnPieChart.setToolTip(_translate("TimePlots", "Visualisation durées"))
        self.btnTextOutput.setToolTip(_translate("TimePlots", "Visualisation durées sous forme de texte\n"
"et exportation CSV"))
        self.lblStart.setText(_translate("TimePlots", "Début:"))
        self.deStart.setToolTip(_translate("TimePlots", "Date de début de la période à considérer"))
        self.deStart.setDisplayFormat(_translate("TimePlots", "yyyy/MM/dd"))
        self.lblEnd.setText(_translate("TimePlots", "Fin:"))
        self.deEnd.setToolTip(_translate("TimePlots", "Date de fin de la période à considérer"))
        self.deEnd.setDisplayFormat(_translate("TimePlots", "yyyy/MM/dd"))
        self.lblHtml.setText(_translate("TimePlots", "En html:"))
        self.edtHtml.setToolTip(_translate("TimePlots", "Représentation textuelle"))
        self.lblCsv.setText(_translate("TimePlots", "Au format CSV:"))
        self.cbCsvFull.setText(_translate("TimePlots", "Complet"))

from . import resources_rc
