# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_timeplots.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimePlots(object):
    def setupUi(self, TimePlots):
        TimePlots.setObjectName("TimePlots")
        TimePlots.resize(609, 436)
        self.layoutTimePlots = QtWidgets.QVBoxLayout(TimePlots)
        self.layoutTimePlots.setObjectName("layoutTimePlots")
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setObjectName("layoutActions")
        self.btnTimeLines = QtWidgets.QToolButton(TimePlots)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_cal_timeline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTimeLines.setIcon(icon)
        self.btnTimeLines.setCheckable(True)
        self.btnTimeLines.setAutoExclusive(True)
        self.btnTimeLines.setObjectName("btnTimeLines")
        self.layoutActions.addWidget(self.btnTimeLines)
        self.btnPieChart = QtWidgets.QToolButton(TimePlots)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/32x32/tool_piechart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPieChart.setIcon(icon1)
        self.btnPieChart.setCheckable(True)
        self.btnPieChart.setAutoExclusive(True)
        self.btnPieChart.setObjectName("btnPieChart")
        self.layoutActions.addWidget(self.btnPieChart)
        self.btnTextOutput = QtWidgets.QToolButton(TimePlots)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_cal_journal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTextOutput.setIcon(icon2)
        self.btnTextOutput.setCheckable(True)
        self.btnTextOutput.setAutoExclusive(True)
        self.btnTextOutput.setObjectName("btnTextOutput")
        self.layoutActions.addWidget(self.btnTextOutput)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutActions.addItem(spacerItem)
        self.btnPrevWeek = QtWidgets.QToolButton(TimePlots)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_revert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevWeek.setIcon(icon3)
        self.btnPrevWeek.setObjectName("btnPrevWeek")
        self.layoutActions.addWidget(self.btnPrevWeek)
        self.btnWorkWeek = QtWidgets.QToolButton(TimePlots)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_cal_workweek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWorkWeek.setIcon(icon4)
        self.btnWorkWeek.setObjectName("btnWorkWeek")
        self.layoutActions.addWidget(self.btnWorkWeek)
        self.btnToday = QtWidgets.QToolButton(TimePlots)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_cal_day.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnToday.setIcon(icon5)
        self.btnToday.setObjectName("btnToday")
        self.layoutActions.addWidget(self.btnToday)
        self.lblStart = QtWidgets.QLabel(TimePlots)
        self.lblStart.setObjectName("lblStart")
        self.layoutActions.addWidget(self.lblStart)
        self.deStart = QtWidgets.QDateEdit(TimePlots)
        self.deStart.setCalendarPopup(True)
        self.deStart.setObjectName("deStart")
        self.layoutActions.addWidget(self.deStart)
        self.lblEnd = QtWidgets.QLabel(TimePlots)
        self.lblEnd.setObjectName("lblEnd")
        self.layoutActions.addWidget(self.lblEnd)
        self.deEnd = QtWidgets.QDateEdit(TimePlots)
        self.deEnd.setCalendarPopup(True)
        self.deEnd.setObjectName("deEnd")
        self.layoutActions.addWidget(self.deEnd)
        self.layoutTimePlots.addLayout(self.layoutActions)
        self.layoutDraw = QtWidgets.QVBoxLayout()
        self.layoutDraw.setSpacing(0)
        self.layoutDraw.setObjectName("layoutDraw")
        self.layoutInfo = QtWidgets.QHBoxLayout()
        self.layoutInfo.setObjectName("layoutInfo")
        self.lblDayDuration = QtWidgets.QLabel(TimePlots)
        self.lblDayDuration.setObjectName("lblDayDuration")
        self.layoutInfo.addWidget(self.lblDayDuration)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutInfo.addItem(spacerItem1)
        self.layoutDraw.addLayout(self.layoutInfo)
        self.frmTextOutput = QtWidgets.QFrame(TimePlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frmTextOutput.sizePolicy().hasHeightForWidth())
        self.frmTextOutput.setSizePolicy(sizePolicy)
        self.frmTextOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTextOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTextOutput.setObjectName("frmTextOutput")
        self.layoutTextOutput = QtWidgets.QVBoxLayout(self.frmTextOutput)
        self.layoutTextOutput.setObjectName("layoutTextOutput")
        self.layoutHtml = QtWidgets.QHBoxLayout()
        self.layoutHtml.setObjectName("layoutHtml")
        self.lblHtml = QtWidgets.QLabel(self.frmTextOutput)
        self.lblHtml.setObjectName("lblHtml")
        self.layoutHtml.addWidget(self.lblHtml)
        self.btnHtmlSave = QtWidgets.QToolButton(self.frmTextOutput)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/32x32/action_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHtmlSave.setIcon(icon6)
        self.btnHtmlSave.setObjectName("btnHtmlSave")
        self.layoutHtml.addWidget(self.btnHtmlSave)
        self.layoutTextOutput.addLayout(self.layoutHtml)
        self.edtHtml = QtWidgets.QTextEdit(self.frmTextOutput)
        self.edtHtml.setObjectName("edtHtml")
        self.layoutTextOutput.addWidget(self.edtHtml)
        self.layoutCsv = QtWidgets.QHBoxLayout()
        self.layoutCsv.setObjectName("layoutCsv")
        self.lblCsv = QtWidgets.QLabel(self.frmTextOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCsv.sizePolicy().hasHeightForWidth())
        self.lblCsv.setSizePolicy(sizePolicy)
        self.lblCsv.setObjectName("lblCsv")
        self.layoutCsv.addWidget(self.lblCsv)
        self.cbCsvFull = QtWidgets.QCheckBox(self.frmTextOutput)
        self.cbCsvFull.setObjectName("cbCsvFull")
        self.layoutCsv.addWidget(self.cbCsvFull)
        self.btnCsvSave = QtWidgets.QToolButton(self.frmTextOutput)
        self.btnCsvSave.setIcon(icon6)
        self.btnCsvSave.setObjectName("btnCsvSave")
        self.layoutCsv.addWidget(self.btnCsvSave)
        self.layoutTextOutput.addLayout(self.layoutCsv)
        self.edtCsv = QtWidgets.QPlainTextEdit(self.frmTextOutput)
        self.edtCsv.setToolTip("")
        self.edtCsv.setObjectName("edtCsv")
        self.layoutTextOutput.addWidget(self.edtCsv)
        self.layoutDraw.addWidget(self.frmTextOutput)
        self.frmTimeLines = QtWidgets.QFrame(TimePlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frmTimeLines.sizePolicy().hasHeightForWidth())
        self.frmTimeLines.setSizePolicy(sizePolicy)
        self.frmTimeLines.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTimeLines.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTimeLines.setObjectName("frmTimeLines")
        self.layoutTimeLines = QtWidgets.QVBoxLayout(self.frmTimeLines)
        self.layoutTimeLines.setContentsMargins(4, 4, 4, 4)
        self.layoutTimeLines.setObjectName("layoutTimeLines")
        self.layoutDraw.addWidget(self.frmTimeLines)
        self.frmPieChart = QtWidgets.QFrame(TimePlots)
        self.frmPieChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPieChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPieChart.setObjectName("frmPieChart")
        self.layoutPieChart = QtWidgets.QVBoxLayout(self.frmPieChart)
        self.layoutPieChart.setContentsMargins(4, 4, 4, 4)
        self.layoutPieChart.setObjectName("layoutPieChart")
        self.layoutDraw.addWidget(self.frmPieChart)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutDraw.addItem(spacerItem2)
        self.layoutDraw.setStretch(1, 1)
        self.layoutDraw.setStretch(2, 1)
        self.layoutDraw.setStretch(3, 1)
        self.layoutTimePlots.addLayout(self.layoutDraw)
        self.buttonBox = QtWidgets.QDialogButtonBox(TimePlots)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutTimePlots.addWidget(self.buttonBox)
        self.layoutTimePlots.setStretch(1, 1)

        self.retranslateUi(TimePlots)
        self.buttonBox.accepted.connect(TimePlots.accept)
        self.buttonBox.rejected.connect(TimePlots.reject)
        QtCore.QMetaObject.connectSlotsByName(TimePlots)
        TimePlots.setTabOrder(self.deStart, self.deEnd)
        TimePlots.setTabOrder(self.deEnd, self.btnHtmlSave)
        TimePlots.setTabOrder(self.btnHtmlSave, self.edtHtml)
        TimePlots.setTabOrder(self.edtHtml, self.cbCsvFull)
        TimePlots.setTabOrder(self.cbCsvFull, self.btnCsvSave)
        TimePlots.setTabOrder(self.btnCsvSave, self.edtCsv)
        TimePlots.setTabOrder(self.edtCsv, self.btnTimeLines)
        TimePlots.setTabOrder(self.btnTimeLines, self.btnPieChart)
        TimePlots.setTabOrder(self.btnPieChart, self.btnTextOutput)
        TimePlots.setTabOrder(self.btnTextOutput, self.btnPrevWeek)
        TimePlots.setTabOrder(self.btnPrevWeek, self.btnWorkWeek)
        TimePlots.setTabOrder(self.btnWorkWeek, self.btnToday)

    def retranslateUi(self, TimePlots):
        _translate = QtCore.QCoreApplication.translate
        TimePlots.setWindowTitle(_translate("TimePlots", "Diagrammes"))
        self.btnTimeLines.setToolTip(_translate("TimePlots", "Visualisation temporelle"))
        self.btnPieChart.setToolTip(_translate("TimePlots", "Visualisation durées"))
        self.btnTextOutput.setToolTip(_translate("TimePlots", "Visualisation durées sous forme de texte\n"
"et exportation CSV"))
        self.btnPrevWeek.setToolTip(_translate("TimePlots", "Semaine précédente"))
        self.btnWorkWeek.setToolTip(_translate("TimePlots", "Modifie les dates pour sélectionner la semaine courante"))
        self.btnToday.setToolTip(_translate("TimePlots", "Modifie les dates pour sélectionner aujourd\'hui"))
        self.lblStart.setText(_translate("TimePlots", "Début:"))
        self.deStart.setToolTip(_translate("TimePlots", "Date de début de la période à considérer"))
        self.deStart.setDisplayFormat(_translate("TimePlots", "yyyy/MM/dd"))
        self.lblEnd.setText(_translate("TimePlots", "Fin:"))
        self.deEnd.setToolTip(_translate("TimePlots", "Date de fin de la période à considérer"))
        self.deEnd.setDisplayFormat(_translate("TimePlots", "yyyy/MM/dd"))
        self.lblDayDuration.setText(_translate("TimePlots", "Durée jour"))
        self.lblHtml.setText(_translate("TimePlots", "En html:"))
        self.btnHtmlSave.setToolTip(_translate("TimePlots", "Sauvegarde au format HTML dans un fichier"))
        self.edtHtml.setToolTip(_translate("TimePlots", "Représentation textuelle"))
        self.lblCsv.setText(_translate("TimePlots", "Au format CSV:"))
        self.cbCsvFull.setText(_translate("TimePlots", "Complet"))
        self.btnCsvSave.setToolTip(_translate("TimePlots", "Sauvegarde au format CSV dans un fichier"))

from . import resources_rc
